server:
  port: 18080

logger:
  level: debug
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: io.seata.samples.sca.provider.dubbo
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
  cloud:
    subscribed-services: ""

spring:
  application:
    name: sca-provider
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_samples?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimeZone=UTC
    username: root
    password: Cc105481
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

mybatis:
  mapper-locations: classpath:mapper/*.xml
seata:
  tx-service-group: rio_seata_group
  registry:
    type: nacos
    nacos:
      username: "nacos"
      password: "nacos"
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      application: seata-server
      namespace: public
      cluster: default


  config:
    type: nacos
    nacos:
      group: SEATA_GROUP
      server-addr: 127.0.0.1:8848
      username: "nacos"
      password: "nacos"
      data-id: seata-server



